import { CurrencyPipe } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../core/api.service';

@Component({
  standalone:true,imports:[ReactiveFormsModule,CurrencyPipe],
  template:`<header class="page"><div><small>ACCOUNTS / {{view().toUpperCase()}}</small><h1>{{title()}}</h1><p>{{description()}}</p></div></header>@if(message()){<div class="notice">{{message()}}</div>}@if(error()){<div class="error">{{error()}}</div>}@if(loading()){<div class="loading">Xogta waa la soo rarayaa…</div>}@else{
    <section class="layout"><form class="panel form" [formGroup]="form" (ngSubmit)="submit()"><h3>{{formTitle()}}</h3>
      @if(view()==='transfers'){<label>From account<select formControlName="FromAccountId">@for(a of data().accounts;track a.AccountId){<option [value]="a.AccountId">{{a.AccountName}} · {{a.CurrentBalance|currency:'USD'}}</option>}</select></label><label>To account<select formControlName="ToAccountId">@for(a of data().accounts;track a.AccountId){<option [value]="a.AccountId">{{a.AccountName}}</option>}</select></label><label>Amount<input type="number" formControlName="Amount"/></label><label>Date<input type="date" formControlName="TransactionDate"/></label><label>Notes<textarea formControlName="Notes"></textarea></label>}
      @if(view()==='deposits'||view()==='withdrawals'){<label>Account<select formControlName="AccountId">@for(a of data().accounts;track a.AccountId){<option [value]="a.AccountId">{{a.AccountName}} · {{a.CurrentBalance|currency:'USD'}}</option>}</select></label><label>Amount<input type="number" formControlName="Amount"/></label><label>Date<input type="date" formControlName="TransactionDate"/></label><label>Description<textarea formControlName="Description"></textarea></label>}
      @if(view()==='reconciliation'){<label>Bank account<select formControlName="AccountId">@for(a of bankAccounts();track a.AccountId){<option [value]="a.AccountId">{{a.AccountName}} · book {{a.CurrentBalance|currency:'USD'}}</option>}</select></label><label>Statement date<input type="date" formControlName="StatementDate"/></label><label>Statement balance<input type="number" formControlName="StatementBalance"/></label><label>Notes<textarea formControlName="Notes"></textarea></label>}
      @if(view()==='expense-categories'){<label>Category name<input formControlName="CategoryName" placeholder="e.g. Utilities"/></label>}
      @if(view()==='payroll-setup'){<label>Employee<select formControlName="EmployeeId">@for(e of data().employees;track e.EmployeeId){<option [value]="e.EmployeeId">{{e.FullName}} · {{e.BasicSalary|currency:'USD'}}</option>}</select></label><label>Month<input type="number" min="1" max="12" formControlName="PayPeriodMonth"/></label><label>Year<input type="number" formControlName="PayPeriodYear"/></label><label>Allowances<input type="number" formControlName="Allowances"/></label><label>Deductions<input type="number" formControlName="Deductions"/></label>}
      @if(view()==='payroll-adjustments'){<label>Pending payroll<select formControlName="PayrollId">@for(p of pendingPayrolls();track p.PayrollId){<option [value]="p.PayrollId">{{p.FullName}} · {{p.PayPeriodMonth}}/{{p.PayPeriodYear}}</option>}</select></label><label>Allowances<input type="number" formControlName="Allowances"/></label><label>Deductions<input type="number" formControlName="Deductions"/></label>}
      <button class="primary" [disabled]="saving()">{{saving()?'Saving…':actionLabel()}}</button></form>
      <section class="panel records"><h3>Recent records</h3><div class="table-wrap"><table><thead><tr>@for(h of headers();track h){<th>{{h}}</th>}</tr></thead><tbody>
        @if(view()==='transfers'){@for(x of data().transfers;track x.AccountTransferId){<tr><td>{{x.TransferDate}}</td><td>{{x.FromAccountName}}</td><td>{{x.ToAccountName}}</td><td>{{x.Amount|currency:'USD'}}</td><td>{{x.Notes||'—'}}</td></tr>}}
        @if(view()==='deposits'||view()==='withdrawals'){@for(x of filteredMovements();track x.LedgerTransactionId){<tr><td>{{x.TransactionDate}}</td><td>{{x.AccountName}}</td><td>{{movementAmount(x)|currency:'USD'}}</td><td>{{x.Description}}</td></tr>}}
        @if(view()==='reconciliation'){@for(x of data().reconciliations;track x.AccountReconciliationId){<tr><td>{{x.StatementDate}}</td><td>{{x.AccountName}}</td><td>{{x.BookBalance|currency:'USD'}}</td><td>{{x.StatementBalance|currency:'USD'}}</td><td><b [class.bad]="+x.Difference!==0">{{x.Difference|currency:'USD'}}</b></td><td>{{x.Status}}</td></tr>}}
        @if(view()==='expense-categories'){@for(x of data().categories;track x.ExpenseCategoryId){<tr><td>{{x.CategoryName}}</td><td>#{{x.ExpenseCategoryId}}</td></tr>}}
        @if(view()==='payroll-setup'||view()==='payroll-adjustments'){@for(x of data().payrolls;track x.PayrollId){<tr><td>{{x.FullName}}</td><td>{{x.PayPeriodMonth}}/{{x.PayPeriodYear}}</td><td>{{x.BasicSalary|currency:'USD'}}</td><td>{{x.Allowances|currency:'USD'}}</td><td>{{x.Deductions|currency:'USD'}}</td><td>{{x.NetSalary|currency:'USD'}}</td><td>{{x.Status}}</td></tr>}}
      </tbody></table></div></section></section>}`,
  styles:[`:host{display:block;color:#243b53}.page{margin-bottom:15px}.page small{color:#2879df;font-size:8px;font-weight:900;letter-spacing:.13em}.page h1{margin:5px 0;font-size:25px}.page p{margin:0;color:#788a9b;font-size:10px}.layout{display:grid;grid-template-columns:360px 1fr;gap:14px}.panel{padding:18px;border:1px solid #dce5ed;border-radius:12px;background:white}.panel h3{margin:0 0 15px;color:#211e75;font-size:13px}.form label{display:grid;gap:6px;margin:12px 0;color:#53687c;font-size:9px;font-weight:800}.form input,.form select,.form textarea{padding:11px;border:1px solid #cedbe7;border-radius:8px;background:#f8fbff}.form textarea{min-height:70px;resize:vertical}.primary{width:100%;padding:12px;border:0;border-radius:8px;background:#211e75;color:white;font-size:9px;font-weight:850}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #edf1f4;text-align:left;font-size:9px;white-space:nowrap}th{color:#758596;background:#f8fafc;font-size:8px}.bad{color:#c13d35}.notice,.error{margin-bottom:12px;padding:10px;border-radius:8px;font-size:9px}.notice{background:#e8f7ef;color:#147a54}.error{background:#fff0ef;color:#b42318}.loading{padding:60px;text-align:center;color:#788a9b}@media(max-width:900px){.layout{grid-template-columns:1fr}}`]
})
export class AccountOperationsComponent implements OnInit{
  view=signal('transfers');data=signal<any>({accounts:[],transfers:[],movements:[],reconciliations:[],categories:[],employees:[],payrolls:[]});loading=signal(true);saving=signal(false);message=signal('');error=signal('');today=new Date().toISOString().slice(0,10);
  form=new FormGroup({FromAccountId:new FormControl<any>(''),ToAccountId:new FormControl<any>(''),AccountId:new FormControl<any>(''),Amount:new FormControl(0,[Validators.min(.01)]),TransactionDate:new FormControl(this.today),StatementDate:new FormControl(this.today),StatementBalance:new FormControl(0),Description:new FormControl(''),Notes:new FormControl(''),CategoryName:new FormControl(''),EmployeeId:new FormControl<any>(''),PayrollId:new FormControl<any>(''),PayPeriodMonth:new FormControl(new Date().getMonth()+1),PayPeriodYear:new FormControl(new Date().getFullYear()),Allowances:new FormControl(0),Deductions:new FormControl(0)});
  constructor(private api:ApiService,private route:ActivatedRoute){}ngOnInit(){this.route.url.subscribe(parts=>{this.view.set(parts.at(-1)?.path||'transfers');this.load()})}
  load(){this.loading.set(true);this.api.get<any>('/account-operations').subscribe({next:r=>{this.data.set(r.data);const a=r.data.accounts[0];this.form.patchValue({FromAccountId:a?.AccountId,ToAccountId:r.data.accounts[1]?.AccountId||a?.AccountId,AccountId:a?.AccountId,EmployeeId:r.data.employees[0]?.EmployeeId,PayrollId:r.data.payrolls.find((p:any)=>p.Status==='Pending')?.PayrollId});this.loading.set(false)},error:e=>{this.error.set(e.error?.message||'Xogta lama soo rari karin.');this.loading.set(false)}})}
  submit(){this.saving.set(true);this.error.set('');const v:any=this.form.getRawValue();let req:any;if(this.view()==='transfers'){const from=this.data().accounts.find((a:any)=>a.AccountId==v.FromAccountId);req=this.api.post('/accounts/transfers',{BranchId:from?.BranchId,FromAccountId:+v.FromAccountId,ToAccountId:+v.ToAccountId,Amount:+v.Amount,TransferDate:v.TransactionDate,Notes:v.Notes})}else if(['deposits','withdrawals'].includes(this.view()))req=this.api.post('/account-operations/movements',{Type:this.view()==='deposits'?'Deposit':'Withdrawal',AccountId:+v.AccountId,Amount:+v.Amount,TransactionDate:v.TransactionDate,Description:v.Description});else if(this.view()==='reconciliation')req=this.api.post('/account-operations/reconciliations',{AccountId:+v.AccountId,StatementDate:v.StatementDate,StatementBalance:+v.StatementBalance,Notes:v.Notes});else if(this.view()==='expense-categories')req=this.api.post('/accounts/expense-categories',{CategoryName:v.CategoryName});else if(this.view()==='payroll-setup'){const e=this.data().employees.find((x:any)=>x.EmployeeId==v.EmployeeId);req=this.api.post('/hrm/payroll',{BranchId:e?.BranchId,EmployeeId:+v.EmployeeId,PayPeriodMonth:+v.PayPeriodMonth,PayPeriodYear:+v.PayPeriodYear,Allowances:+v.Allowances,Deductions:+v.Deductions})}else req=this.api.put(`/account-operations/payrolls/${v.PayrollId}`,{Allowances:+v.Allowances,Deductions:+v.Deductions});req.subscribe({next:(r:any)=>{this.message.set(r.message);this.saving.set(false);this.load()},error:(e:any)=>{this.error.set(e.error?.message||Object.values(e.error?.errors||{}).flat().join(' ')||'Operation failed.');this.saving.set(false)}})}
  title(){return({transfers:'Account Transfers',deposits:'Account Deposits',withdrawals:'Account Withdrawals',reconciliation:'Bank Reconciliation','expense-categories':'Expense Categories','payroll-setup':'Payroll Setup','payroll-adjustments':'Payroll Adjustments'}as any)[this.view()]}
  description(){return({transfers:'Move funds safely between school accounts.',deposits:'Record money deposited into an account.',withdrawals:'Record controlled withdrawals with a balanced ledger.',reconciliation:'Compare the system balance with a bank statement.','expense-categories':'Create categories used to classify school expenses.','payroll-setup':'Prepare employee payroll for a selected period.','payroll-adjustments':'Update allowances and deductions on pending payroll.'}as any)[this.view()]}
  formTitle(){return this.view()==='expense-categories'?'New category':this.view()==='payroll-adjustments'?'Adjust pending payroll':this.title()}
  actionLabel(){return({transfers:'Post transfer',deposits:'Post deposit',withdrawals:'Post withdrawal',reconciliation:'Save reconciliation','expense-categories':'Add category','payroll-setup':'Prepare payroll','payroll-adjustments':'Save adjustment'}as any)[this.view()]}
  headers(){return({transfers:['Date','From','To','Amount','Notes'],deposits:['Date','Account','Amount','Description'],withdrawals:['Date','Account','Amount','Description'],reconciliation:['Date','Account','Book','Statement','Difference','Status'],'expense-categories':['Category','ID'],'payroll-setup':['Employee','Period','Basic','Allowances','Deductions','Net','Status'],'payroll-adjustments':['Employee','Period','Basic','Allowances','Deductions','Net','Status']}as any)[this.view()]||[]}
  bankAccounts(){return this.data().accounts.filter((x:any)=>['Bank','MobileMoney'].includes(x.AccountType))}pendingPayrolls(){return this.data().payrolls.filter((x:any)=>x.Status==='Pending')}filteredMovements(){const type=this.view()==='deposits'?'Deposit':'Withdrawal';return this.data().movements.filter((x:any)=>x.ReferenceType===type)}movementAmount(x:any){return x.ReferenceType==='Deposit'?x.Debit:x.Credit}
}
