export const Permissions = {
  StudentsView: 'students.view',
  StudentsCreate: 'students.create',
  StudentsUpdate: 'students.update',
  StudentsPromote: 'students.promote',
  AttendanceTake: 'attendance.take',
  AttendanceCorrect: 'attendance.correct',
  AcademicManage: 'academic.manage',
  QuranManage: 'quran.manage',
  FinanceManage: 'finance.manage',
  AccountsManage: 'accounts.manage',
  ExaminationsManage: 'examinations.manage',
  HrmManage: 'hrm.manage',
  UsersManage: 'users.manage',
  RolesManage: 'roles.manage',
  ReportsView: 'reports.view',
  AuditView: 'audit.view',
  SettingsManage: 'settings.manage',
  SmsConfigure: 'sms.configure',
  SmsSend: 'sms.send',
  FeedbackManage: 'feedback.manage',
} as const;
