import { Permissions } from '../core/permissions/permissions.constants';
export interface NavigationItem {
  label: string;
  route?: string;
  permission?: string;
  icon?: string;
  children?: NavigationItem[];
}
export const MADAARIS_NAVIGATION: NavigationItem[] = [
  { label: 'Home', route: '/dashboard', icon: '⌂' },
  {
    label: 'Academic',
    icon: '▦',
    permission: Permissions.AcademicManage,
    children: [
      { label: 'Academic Years', route: '/academic/academic-years' },
      { label: 'Timetables', route: '/academic/timetables' },
      { label: 'Levels', route: '/academic/levels' },
      { label: 'Subjects', route: '/academic/subjects' },
      { label: 'Lessons', route: '/academic/lessons' },
      { label: 'Classes', route: '/academic/classes' },
      { label: 'Class Promotions', route: '/academic/promotions' },
      { label: 'Graduations', route: '/academic/graduations' },
      { label: 'Shifts', route: '/academic/shifts' },
    ],
  },
  {
    label: 'Students',
    icon: '♙',
    permission: Permissions.StudentsView,
    children: [
      { label: 'All Students', route: '/students' },
      { label: 'Add Student', route: '/students/new', permission: Permissions.StudentsCreate },
      { label: 'Graduation', route: '/students/graduation' },
      { label: 'Inactive Students', route: '/students/inactive' },
      {
        label: 'Discipline',
        route: '/students/discipline',
        permission: Permissions.StudentsUpdate,
      },
      { label: 'Parents / Guardians', route: '/students/guardians' },
    ],
  },
  {
    label: 'HRM',
    icon: '♟',
    permission: Permissions.HrmManage,
    children: [
      { label: 'Employees', route: '/hrm/employees' },
      { label: 'Employee Attendance', route: '/hrm/attendance' },
      { label: 'Attendance Reports', route: '/hrm/attendance-reports' },
      { label: 'Teachers', route: '/hrm/teachers' },
      { label: 'Teacher Assignments', route: '/hrm/teacher-assignments' },
    ],
  },
  {
    label: 'Examinations',
    icon: '▤',
    permission: Permissions.ExaminationsManage,
    children: [
      { label: 'Exam Types', route: '/examinations/types' },
      { label: 'Add Exam', route: '/examinations/new' },
      { label: 'View Exams', route: '/examinations/list' },
      { label: 'Manage Exams', route: '/examinations/manage' },
      { label: 'Mark Sheets', route: '/examinations/mark-sheets' },
      { label: 'Top Students', route: '/examinations/top-students' },
      { label: 'Low Students', route: '/examinations/low-students' },
      { label: 'Exam Schedules', route: '/examinations/schedules' },
      { label: 'ID Cards', route: '/examinations/id-cards' },
      { label: 'Clearance Cards', route: '/examinations/clearance-cards' },
    ],
  },
  {
    label: 'Attendance',
    icon: '✓',
    permission: Permissions.AttendanceTake,
    children: [
      { label: 'Take Attendance', route: '/attendance/take' },
      { label: 'View Attendance', route: '/attendance/history' },
      { label: 'Corrections & Missing', route: '/attendance/corrections' },
      { label: 'Attendance Reports', route: '/attendance/reports' },
    ],
  },
  {
    label: 'Islamic / Qur’an',
    icon: '☾',
    permission: Permissions.QuranManage,
    children: [
      { label: 'Memorization', route: '/quran/memorization' },
      { label: 'View Memorization', route: '/quran/memorization-records' },
      { label: 'Memorization Reports', route: '/quran/memorization-reports' },
      { label: 'Qur’an Assignments', route: '/quran/assignments' },
      { label: 'Surah List', route: '/quran/surahs' },
      { label: 'Farbar', route: '/quran/farbar' },
      { label: 'Subac', route: '/quran/subac' },
      { label: 'Dareeris', route: '/quran/dareeris' },
      { label: 'Qur’an Lessons', route: '/quran/lessons' },
      { label: 'Mistake Types', route: '/quran/mistakes' },
      { label: 'Qur’an Examinations', route: '/quran/examinations' },
      { label: 'Qur’an Reports', route: '/quran/reports' },
    ],
  },
  {
    label: 'Finance',
    icon: '$',
    permission: Permissions.FinanceManage,
    children: [
      { label: 'Receive Fee', route: '/finance/receive-fee' },
      { label: 'Receipt List', route: '/finance/payments' },
      { label: 'View Invoices', route: '/finance/invoices' },
      { label: 'All Charges', route: '/finance/all-charges' },
      { label: 'Single Charge', route: '/finance/single-charge' },
      { label: 'Fee Types', route: '/finance/fee-types' },
      { label: 'Student Discounts', route: '/finance/discounts' },
      { label: 'Scholarships', route: '/finance/scholarships' },
      { label: 'Fee Responsibilities', route: '/finance/fee-responsibilities' },
      { label: 'Student Adjustments', route: '/finance/student-adjustments' },
    ],
  },
  {
    label: 'Accounts',
    icon: '▣',
    permission: Permissions.AccountsManage,
    children: [
      { label: 'Accounts', route: '/finance/accounts' },
      { label: 'Account Transfers', route: '/accounts/transfers' },
      { label: 'Account Deposits', route: '/accounts/deposits' },
      { label: 'Account Withdrawals', route: '/accounts/withdrawals' },
      { label: 'Bank Reconciliation', route: '/accounts/reconciliation' },
      { label: 'Expenses', route: '/finance/expenses' },
      { label: 'Expense Categories', route: '/accounts/expense-categories' },
      { label: 'Payroll Setup', route: '/accounts/payroll-setup' },
      { label: 'Payroll List', route: '/hrm/payroll' },
      { label: 'Payroll Adjustments', route: '/accounts/payroll-adjustments' },
    ],
  },
  { label: 'Users', route: '/users', icon: '♟', permission: Permissions.UsersManage },
  { label: 'Talo iyo Ra’yi', route: '/feedback', icon: '✎' },
  { label: 'Reports', route: '/reports', icon: '▥', permission: Permissions.ReportsView },
  {
    label: 'SMS Management',
    icon: '✉',
    children: [
      { label: 'Guudmarka SMS', route: '/sms/dashboard', permission: Permissions.SmsViewDashboard },
      { label: 'Dir SMS', route: '/sms/send', permission: Permissions.SmsSendIndividual },
      {
        label: 'Xusuusin Lacag Wadajir',
        route: '/sms/bulk-fee-reminder',
        permission: Permissions.SmsSendBulk,
      },
      {
        label: 'Qaababka Fariimaha',
        route: '/sms/templates',
        permission: Permissions.SmsManageTemplates,
      },
      {
        label: 'Jadwalka SMS',
        route: '/sms/scheduled-sms',
        permission: Permissions.SmsManageSchedules,
      },
      { label: 'Taariikhda SMS', route: '/sms/history', permission: Permissions.SmsViewHistory },
      { label: 'Dejinta SMS', route: '/sms/settings', permission: Permissions.SmsManageSettings },
    ],
  },
  {
    label: 'Settings',
    icon: '⚙',
    permission: Permissions.SettingsManage,
    children: [
      { label: 'School Profile', route: '/settings' },
      { label: 'Branches', route: '/settings/branches' },
      { label: 'Roles', route: '/roles-permissions', permission: Permissions.RolesManage },
      { label: 'Permissions', route: '/permissions', permission: Permissions.RolesManage },
      { label: 'Announcements', route: '/settings/announcements' },
      { label: 'Fee Permissions', route: '/settings/fee-permissions' },
      { label: 'System Settings', route: '/settings/system' },
      { label: 'Audit Log', route: '/audit', permission: Permissions.AuditView },
    ],
  },
];
