<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        $timestamps = function (Blueprint $t): void { $t->timestamp('CreatedAt')->nullable(); $t->timestamp('UpdatedAt')->nullable(); };
        Schema::create('Tenants', function (Blueprint $t) use ($timestamps) { $t->id('TenantId'); $t->string('Name'); $t->string('Slug')->unique(); $t->string('Status')->default('Active'); $t->string('Timezone')->default('Africa/Mogadishu'); $t->string('Currency', 3)->default('USD'); $timestamps($t); });
        Schema::table('Users', fn (Blueprint $t) => $t->foreign('TenantId')->references('TenantId')->on('Tenants')->nullOnDelete());
        Schema::create('Branches', function (Blueprint $t) use ($timestamps) { $t->id('BranchId'); $t->foreignId('TenantId')->constrained('Tenants', 'TenantId')->cascadeOnDelete(); $t->string('Name'); $t->string('Code'); $t->string('Status')->default('Active'); $timestamps($t); $t->unique(['TenantId','Code']); });
        Schema::create('UserBranches', function (Blueprint $t) { $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('UserId')->constrained('Users','UserId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId')->cascadeOnDelete(); $t->primary(['UserId','BranchId']); $t->index(['TenantId','BranchId']); });
        Schema::create('AcademicYears', function (Blueprint $t) use ($timestamps) { $t->id('AcademicYearId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->string('Name'); $t->date('StartDate'); $t->date('EndDate'); $t->boolean('IsDefault')->default(false); $t->string('Status')->default('Active'); $timestamps($t); $t->unique(['TenantId','Name']); });
        Schema::create('Levels', function (Blueprint $t) use ($timestamps) { $t->id('LevelId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->string('Name'); $t->string('Code'); $t->unsignedInteger('SequenceNo')->default(1); $t->decimal('MinimumPromotionScore',5,2)->default(50); $t->string('Status')->default('Active'); $timestamps($t); $t->unique(['TenantId','Code']); });
        Schema::create('Shifts', function (Blueprint $t) use ($timestamps) { $t->id('ShiftId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->string('Name'); $t->time('StartTime'); $t->time('EndTime'); $t->string('Status')->default('Active'); $timestamps($t); $t->unique(['TenantId','Name']); });
        Schema::create('Classes', function (Blueprint $t) { $t->id('ClassId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId'); $t->foreignId('AcademicYearId')->constrained('AcademicYears','AcademicYearId'); $t->foreignId('LevelId')->constrained('Levels','LevelId'); $t->foreignId('ShiftId')->constrained('Shifts','ShiftId'); $t->string('Name'); $t->string('Code'); $t->unsignedInteger('Capacity')->default(30); $t->string('Status')->default('Active'); $t->timestamps(null,'CreatedAt','UpdatedAt'); $t->unique(['TenantId','AcademicYearId','Code']); $t->index(['TenantId','BranchId']); });
        Schema::create('Students', function (Blueprint $t) { $t->id('StudentId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId'); $t->string('AdmissionNo'); $t->string('FirstName'); $t->string('MiddleName')->nullable(); $t->string('LastName'); $t->string('Gender'); $t->date('DateOfBirth')->nullable(); $t->string('Phone')->nullable(); $t->date('AdmissionDate'); $t->string('WelfareStatus')->default('Normal'); $t->string('Status')->default('Active'); $t->timestamps(null,'CreatedAt','UpdatedAt'); $t->unique(['TenantId','AdmissionNo']); $t->index(['TenantId','BranchId','Status']); });
        Schema::create('Enrollments', function (Blueprint $t) { $t->id('EnrollmentId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId'); $t->foreignId('StudentId')->constrained('Students','StudentId'); $t->foreignId('ClassId')->constrained('Classes','ClassId'); $t->foreignId('AcademicYearId')->constrained('AcademicYears','AcademicYearId'); $t->date('EnrolledAt'); $t->string('Status')->default('Active'); $t->timestamps(null,'CreatedAt','UpdatedAt'); $t->unique(['TenantId','StudentId','AcademicYearId']); });
        Schema::create('Attendance', function (Blueprint $t) { $t->id('AttendanceId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId'); $t->foreignId('StudentId')->constrained('Students','StudentId'); $t->foreignId('ClassId')->constrained('Classes','ClassId'); $t->date('AttendanceDate'); $t->string('Session')->default('Daily'); $t->string('Status'); $t->foreignId('MarkedBy')->constrained('Users','UserId'); $t->timestamps(null,'CreatedAt','UpdatedAt'); $t->unique(['TenantId','StudentId','AttendanceDate','Session']); });
        Schema::create('QuranAssignments', function (Blueprint $t) { $t->id('QuranAssignmentId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId'); $t->foreignId('StudentId')->constrained('Students','StudentId'); $t->foreignId('TeacherId')->constrained('Users','UserId'); $t->string('LessonType'); $t->unsignedTinyInteger('SurahNo'); $t->unsignedSmallInteger('FromAyah'); $t->unsignedSmallInteger('ToAyah'); $t->date('AssignedDate'); $t->date('DueDate'); $t->unsignedInteger('RepetitionTarget')->default(1); $t->string('Status')->default('Assigned'); $t->text('Notes')->nullable(); $t->timestamps(null,'CreatedAt','UpdatedAt'); $t->index(['TenantId','BranchId','Status']); });
        Schema::create('Invoices', function (Blueprint $t) { $t->id('InvoiceId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId'); $t->foreignId('StudentId')->constrained('Students','StudentId'); $t->string('InvoiceNo'); $t->decimal('Total',14,2); $t->decimal('Balance',14,2); $t->date('DueDate'); $t->string('Status')->default('Issued'); $t->timestamps(null,'CreatedAt','UpdatedAt'); $t->unique(['TenantId','InvoiceNo']); });
        Schema::create('Payments', function (Blueprint $t) { $t->id('PaymentId'); $t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete(); $t->foreignId('BranchId')->constrained('Branches','BranchId'); $t->foreignId('StudentId')->constrained('Students','StudentId'); $t->foreignId('InvoiceId')->constrained('Invoices','InvoiceId'); $t->string('ReceiptNo'); $t->uuid('IdempotencyKey'); $t->decimal('Amount',14,2); $t->string('Method'); $t->string('Status')->default('Completed'); $t->foreignId('ReceivedBy')->constrained('Users','UserId'); $t->timestamps(null,'CreatedAt','UpdatedAt'); $t->unique(['TenantId','ReceiptNo']); $t->unique(['TenantId','IdempotencyKey']); });
        Schema::create('AuditLogs', function (Blueprint $t) { $t->id('AuditLogId'); $t->unsignedBigInteger('TenantId')->nullable()->index(); $t->unsignedBigInteger('BranchId')->nullable(); $t->unsignedBigInteger('UserId')->nullable(); $t->string('Action'); $t->string('EntityType'); $t->string('EntityId')->nullable(); $t->json('BeforeData')->nullable(); $t->json('AfterData')->nullable(); $t->string('IpAddress',45)->nullable(); $t->text('UserAgent')->nullable(); $t->uuid('RequestId'); $t->timestamp('CreatedAt')->useCurrent(); $t->index(['TenantId','EntityType','EntityId']); });
    }
    public function down(): void { foreach (['AuditLogs','Payments','Invoices','QuranAssignments','Attendance','Enrollments','Students','Classes','Shifts','Levels','AcademicYears','UserBranches','Branches'] as $table) Schema::dropIfExists($table); Schema::table('Users', fn(Blueprint $t) => $t->dropForeign(['TenantId'])); Schema::dropIfExists('Tenants'); }
};
