<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::table('Students',function(Blueprint $t){$t->string('Address')->nullable();$t->string('PhotoPath')->nullable();$t->text('HealthNotes')->nullable();$t->unsignedInteger('Version')->default(1);$t->softDeletes('DeletedAt');});
  Schema::create('StudentDocuments',function(Blueprint $t){$t->id('StudentDocumentId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->string('DocumentType',80);$t->string('OriginalName');$t->string('StoragePath');$t->string('MimeType',100);$t->unsignedBigInteger('FileSize');$t->unsignedBigInteger('UploadedByUserId');$t->timestamp('CreatedAt')->useCurrent();$t->index(['TenantId','StudentId']);});
  Schema::create('StudentClearances',function(Blueprint $t){$t->id('StudentClearanceId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->foreignId('EnrollmentId')->constrained('Enrollments','EnrollmentId');$t->boolean('AcademicCleared')->default(false);$t->boolean('QuranCleared')->default(false);$t->boolean('FinanceCleared')->default(false);$t->boolean('DisciplineCleared')->default(false);$t->boolean('AssetsCleared')->default(false);$t->string('Status')->default('Pending');$t->unsignedBigInteger('ApprovedByUserId')->nullable();$t->timestamp('ApprovedAt')->nullable();$t->text('Notes')->nullable();$t->timestamp('CreatedAt')->useCurrent();$t->unique(['TenantId','StudentId','EnrollmentId']);});
  Schema::create('Graduations',function(Blueprint $t){$t->id('GraduationId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('StudentId')->constrained('Students','StudentId');$t->foreignId('EnrollmentId')->constrained('Enrollments','EnrollmentId');$t->date('GraduationDate');$t->string('CertificateNo');$t->string('ClearanceStatus');$t->string('ApprovalStatus')->default('Pending');$t->unsignedBigInteger('ApprovedByUserId')->nullable();$t->text('Notes')->nullable();$t->timestamp('CreatedAt')->useCurrent();$t->unique(['TenantId','CertificateNo']);$t->unique(['TenantId','StudentId','EnrollmentId']);});
  Schema::create('StudentTransfers',function(Blueprint $t){$t->id('StudentTransferId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->foreignId('FromBranchId')->constrained('Branches','BranchId');$t->unsignedBigInteger('ToBranchId')->nullable();$t->string('ExternalDestination')->nullable();$t->date('TransferDate');$t->string('Reason');$t->string('Status')->default('Pending');$t->unsignedBigInteger('ApprovedByUserId')->nullable();$t->timestamp('CreatedAt')->useCurrent();$t->index(['TenantId','StudentId']);});
 }
 public function down():void {foreach(['StudentTransfers','Graduations','StudentClearances','StudentDocuments'] as $x)Schema::dropIfExists($x);Schema::table('Students',function(Blueprint $t){$t->dropColumn(['Address','PhotoPath','HealthNotes','Version','DeletedAt']);});}
};
