<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('Roles', function(Blueprint $t){$t->id('RoleId');$t->unsignedBigInteger('TenantId')->nullable()->index();$t->string('RoleName',80);$t->boolean('IsSystemRole')->default(false);$t->timestamp('CreatedAt')->useCurrent();$t->unique(['TenantId','RoleName']);$t->foreign('TenantId')->references('TenantId')->on('Tenants')->cascadeOnDelete();});
        Schema::create('Permissions', function(Blueprint $t){$t->id('PermissionId');$t->string('ModuleName',80);$t->string('ActionName',40);$t->string('PermissionKey',150)->unique();});
        Schema::create('RolePermissions', function(Blueprint $t){$t->id('RolePermissionId');$t->foreignId('RoleId')->constrained('Roles','RoleId')->cascadeOnDelete();$t->foreignId('PermissionId')->constrained('Permissions','PermissionId')->cascadeOnDelete();$t->unique(['RoleId','PermissionId']);});
        Schema::create('UserRoles', function(Blueprint $t){$t->id('UserRoleId');$t->unsignedBigInteger('TenantId')->index();$t->foreignId('UserId')->constrained('Users','UserId')->cascadeOnDelete();$t->foreignId('RoleId')->constrained('Roles','RoleId')->cascadeOnDelete();$t->unique(['UserId','RoleId']);});

        Schema::create('Subjects', function(Blueprint $t){$t->id('SubjectId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('SubjectName',100);$t->string('SubjectCode',20)->nullable();$t->string('SubjectType',30)->default('Academic');$t->decimal('MaximumMark',6,2)->default(100);$t->decimal('PassMark',6,2)->default(50);$t->boolean('IsActive')->default(true);$t->unique(['TenantId','SubjectCode']);});
        Schema::create('Lessons', function(Blueprint $t){$t->id('LessonId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('SubjectId')->constrained('Subjects','SubjectId')->cascadeOnDelete();$t->string('LessonTitle',150);$t->integer('SortOrder')->default(0);$t->index(['TenantId','SubjectId']);});
        Schema::create('TimeTables', function(Blueprint $t){$t->id('TimeTableId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('ClassId')->constrained('Classes','ClassId')->cascadeOnDelete();$t->foreignId('SubjectId')->constrained('Subjects','SubjectId');$t->unsignedBigInteger('TeacherId')->nullable();$t->unsignedTinyInteger('DayOfWeek');$t->time('StartTime');$t->time('EndTime');$t->string('Room',50)->nullable();$t->index(['TenantId','BranchId','DayOfWeek']);});
        Schema::create('PromotionLogs', function(Blueprint $t){$t->id('PromotionLogId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->unsignedBigInteger('FromClassId')->nullable();$t->unsignedBigInteger('ToClassId')->nullable();$t->foreignId('FromAcademicYearId')->constrained('AcademicYears','AcademicYearId');$t->foreignId('ToAcademicYearId')->constrained('AcademicYears','AcademicYearId');$t->string('Status')->default('Promoted');$t->unsignedBigInteger('PromotedByUserId')->nullable();$t->timestamp('CreatedAt')->useCurrent();$t->index(['TenantId','StudentId']);});

        Schema::create('Guardians', function(Blueprint $t){$t->id('GuardianId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('FullName',150);$t->string('Gender',10)->nullable();$t->string('Relationship',50)->nullable();$t->string('PrimaryPhone',30);$t->string('SecondaryPhone',30)->nullable();$t->string('Email',150)->nullable();$t->string('Address')->nullable();$t->string('NationalId',80)->nullable();$t->boolean('SmsConsent')->default(true);$t->index(['TenantId','PrimaryPhone']);});
        Schema::create('StudentGuardians', function(Blueprint $t){$t->id('StudentGuardianId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->foreignId('GuardianId')->constrained('Guardians','GuardianId')->cascadeOnDelete();$t->boolean('IsPrimary')->default(false);$t->boolean('IsFeeResponsible')->default(false);$t->unique(['TenantId','StudentId','GuardianId']);});
        Schema::create('DisciplineRecords', function(Blueprint $t){$t->id('DisciplineRecordId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->date('IncidentDate');$t->text('Description');$t->string('ActionTaken')->nullable();$t->unsignedBigInteger('ReportedByUserId')->nullable();$t->timestamp('CreatedAt')->useCurrent();$t->index(['TenantId','StudentId','IncidentDate']);});

        Schema::create('Departments', function(Blueprint $t){$t->id('DepartmentId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('DepartmentName',100);$t->unique(['TenantId','DepartmentName']);});
        Schema::create('Designations', function(Blueprint $t){$t->id('DesignationId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('DesignationName',100);$t->unique(['TenantId','DesignationName']);});
        Schema::create('Employees', function(Blueprint $t){$t->id('EmployeeId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->unsignedBigInteger('UserId')->nullable();$t->string('EmployeeNo',30);$t->string('FullName',150);$t->string('Gender',10)->nullable();$t->string('Phone',30)->nullable();$t->string('Email',150)->nullable();$t->unsignedBigInteger('DepartmentId')->nullable();$t->unsignedBigInteger('DesignationId')->nullable();$t->date('HireDate')->nullable();$t->decimal('BasicSalary',12,2)->default(0);$t->boolean('IsTeacher')->default(false);$t->string('Status')->default('Active');$t->timestamp('CreatedAt')->useCurrent();$t->unique(['TenantId','EmployeeNo']);$t->index(['TenantId','BranchId','Status']);});
        Schema::create('Teachers', function(Blueprint $t){$t->id('TeacherId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('EmployeeId')->constrained('Employees','EmployeeId')->cascadeOnDelete()->unique();$t->string('Specialization',150)->nullable();$t->string('QualificationLevel',100)->nullable();});
        Schema::create('TeacherAssignments', function(Blueprint $t){$t->id('TeacherAssignmentId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('TeacherId')->constrained('Teachers','TeacherId')->cascadeOnDelete();$t->foreignId('ClassId')->constrained('Classes','ClassId');$t->unsignedBigInteger('SubjectId')->nullable();$t->foreignId('AcademicYearId')->constrained('AcademicYears','AcademicYearId');$t->unique(['TenantId','TeacherId','ClassId','SubjectId','AcademicYearId']);});

        Schema::create('ExamTypes', function(Blueprint $t){$t->id('ExamTypeId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('TypeName',80);$t->unique(['TenantId','TypeName']);});
        Schema::create('Exams', function(Blueprint $t){$t->id('ExamId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('AcademicYearId')->constrained('AcademicYears','AcademicYearId');$t->foreignId('ExamTypeId')->constrained('ExamTypes','ExamTypeId');$t->foreignId('ClassId')->constrained('Classes','ClassId');$t->foreignId('SubjectId')->constrained('Subjects','SubjectId');$t->string('ExamTitle',150);$t->decimal('MaximumMark',6,2)->default(100);$t->decimal('PassMark',6,2)->default(50);$t->string('Status')->default('Draft');$t->index(['TenantId','BranchId','Status']);});
        Schema::create('ExamSchedules', function(Blueprint $t){$t->id('ExamScheduleId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('ExamId')->constrained('Exams','ExamId')->cascadeOnDelete();$t->date('ExamDate');$t->time('StartTime')->nullable();$t->time('EndTime')->nullable();$t->string('RoomName',50)->nullable();});
        Schema::create('StudentMarks', function(Blueprint $t){$t->id('StudentMarkId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('ExamId')->constrained('Exams','ExamId')->cascadeOnDelete();$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->decimal('MarksObtained',6,2);$t->string('Grade',10)->nullable();$t->string('Remarks',150)->nullable();$t->unsignedBigInteger('EnteredByUserId')->nullable();$t->string('Status')->default('Draft');$t->timestamp('CreatedAt')->useCurrent();$t->unique(['TenantId','ExamId','StudentId']);});

        Schema::create('Surahs', function(Blueprint $t){$t->unsignedTinyInteger('SurahId')->primary();$t->string('NameArabic',100);$t->string('NameEnglish',100);$t->unsignedSmallInteger('TotalAyahs');$t->unsignedTinyInteger('JuzNumberStart')->nullable();});
        Schema::create('QuranErrorTypes', function(Blueprint $t){$t->id('QuranErrorTypeId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('ErrorName',100);$t->string('Description')->nullable();$t->unique(['TenantId','ErrorName']);});
        Schema::create('QuranLessons', function(Blueprint $t){$t->id('QuranLessonId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('LessonName',100);$t->string('Description')->nullable();$t->json('Settings')->nullable();$t->unique(['TenantId','LessonName']);});
        Schema::create('QuranProgressLogs', function(Blueprint $t){$t->id('QuranProgressLogId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->unsignedBigInteger('TeacherId');$t->string('RecordType');$t->unsignedTinyInteger('SurahFromId');$t->unsignedSmallInteger('AyahFrom');$t->unsignedTinyInteger('SurahToId');$t->unsignedSmallInteger('AyahTo');$t->string('Status')->default('New');$t->decimal('AccuracyScore',5,2)->nullable();$t->decimal('FluencyScore',5,2)->nullable();$t->decimal('TajweedScore',5,2)->nullable();$t->unsignedBigInteger('ErrorTypeId')->nullable();$t->string('Notes')->nullable();$t->date('RecordDate');$t->timestamp('CreatedAt')->useCurrent();$t->index(['TenantId','StudentId','RecordDate']);});

        Schema::create('FeeTypes', function(Blueprint $t){$t->id('FeeTypeId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('FeeTypeName',100);$t->boolean('IsActive')->default(true);$t->unique(['TenantId','FeeTypeName']);});
        Schema::create('InvoiceItems', function(Blueprint $t){$t->id('InvoiceItemId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('InvoiceId')->constrained('Invoices','InvoiceId')->cascadeOnDelete();$t->foreignId('FeeTypeId')->constrained('FeeTypes','FeeTypeId');$t->string('Description',150)->nullable();$t->decimal('Amount',12,2);$t->index(['TenantId','InvoiceId']);});
        Schema::create('StudentDiscounts', function(Blueprint $t){$t->id('StudentDiscountId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('StudentId')->constrained('Students','StudentId')->cascadeOnDelete();$t->string('DiscountType');$t->decimal('Percentage',5,2)->nullable();$t->decimal('FixedAmount',12,2)->nullable();$t->string('Reason')->nullable();$t->unsignedBigInteger('ApprovedByUserId')->nullable();$t->date('StartDate')->nullable();$t->date('EndDate')->nullable();$t->boolean('IsActive')->default(true);$t->index(['TenantId','StudentId','IsActive']);});
        Schema::create('Accounts', function(Blueprint $t){$t->id('AccountId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->string('AccountName',100);$t->string('AccountType');$t->string('AccountNumber',60)->nullable();$t->decimal('OpeningBalance',14,2)->default(0);$t->decimal('CurrentBalance',14,2)->default(0);$t->boolean('IsActive')->default(true);$t->unique(['TenantId','AccountName']);});
        Schema::create('ExpenseCategories', function(Blueprint $t){$t->id('ExpenseCategoryId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('CategoryName',100);$t->unique(['TenantId','CategoryName']);});
        Schema::create('Expenses', function(Blueprint $t){$t->id('ExpenseId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->foreignId('BranchId')->constrained('Branches','BranchId');$t->foreignId('CategoryId')->constrained('ExpenseCategories','ExpenseCategoryId');$t->foreignId('AccountId')->constrained('Accounts','AccountId');$t->decimal('Amount',14,2);$t->string('Description')->nullable();$t->date('ExpenseDate');$t->unsignedBigInteger('CreatedByUserId')->nullable();$t->string('Status')->default('Draft');$t->index(['TenantId','BranchId','ExpenseDate']);});

        Schema::create('Announcements', function(Blueprint $t){$t->id('AnnouncementId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('Title',150);$t->text('Body');$t->string('AudienceType')->default('All');$t->timestamp('PublishedAt')->nullable();$t->unsignedBigInteger('CreatedByUserId')->nullable();});
        Schema::create('Suggestions', function(Blueprint $t){$t->id('SuggestionId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->unsignedBigInteger('SubmittedByUserId')->nullable();$t->string('Category')->default('Suggestion');$t->string('Priority')->default('Normal');$t->string('Subject',150);$t->text('Description');$t->boolean('IsAnonymous')->default(false);$t->text('Response')->nullable();$t->string('Status')->default('Open');$t->timestamp('CreatedAt')->useCurrent();$t->timestamp('ResolvedAt')->nullable();});
        Schema::create('SmsSettings', function(Blueprint $t){$t->id('SmsSettingId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete()->unique();$t->string('ProviderName',80)->nullable();$t->text('EncryptedCredentials')->nullable();$t->string('SenderId',30)->nullable();$t->boolean('IsActive')->default(true);});
        Schema::create('SmsTemplates', function(Blueprint $t){$t->id('SmsTemplateId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('TemplateName',100);$t->string('TemplateBody',500);$t->unique(['TenantId','TemplateName']);});
        Schema::create('SmsLogs', function(Blueprint $t){$t->id('SmsLogId');$t->foreignId('TenantId')->constrained('Tenants','TenantId')->cascadeOnDelete();$t->string('RecipientPhone',30);$t->string('MessageBody',500);$t->string('Status')->default('Queued');$t->string('FailedReason')->nullable();$t->timestamp('SentAt')->nullable();$t->unsignedBigInteger('CreatedByUserId')->nullable();$t->timestamp('CreatedAt')->useCurrent();$t->index(['TenantId','Status','CreatedAt']);});
    }

    public function down(): void
    {
        foreach (['SmsLogs','SmsTemplates','SmsSettings','Suggestions','Announcements','Expenses','ExpenseCategories','Accounts','StudentDiscounts','InvoiceItems','FeeTypes','QuranProgressLogs','QuranLessons','QuranErrorTypes','Surahs','StudentMarks','ExamSchedules','Exams','ExamTypes','TeacherAssignments','Teachers','Employees','Designations','Departments','DisciplineRecords','StudentGuardians','Guardians','PromotionLogs','TimeTables','Lessons','Subjects','UserRoles','RolePermissions','Permissions','Roles'] as $table) Schema::dropIfExists($table);
    }
};
