<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Tenancy\TenantContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;
class HrmController extends Controller
{
 public function employees(Request $r,TenantContext $t){if($r->isMethod('post')){$d=$r->validate(['BranchId'=>['required','integer'],'EmployeeNo'=>['required','string'],'FullName'=>['required','string'],'Gender'=>['nullable',Rule::in(['Male','Female'])],'Phone'=>['nullable','string'],'Email'=>['nullable','email'],'HireDate'=>['nullable','date'],'BasicSalary'=>['required','numeric','gte:0'],'IsTeacher'=>['boolean'],'Status'=>['required',Rule::in(['Active','Inactive','Suspended','Terminated'])]]);$id=DB::table('Employees')->insertGetId(['TenantId'=>$t->id(),'CreatedAt'=>now(),...$d],'EmployeeId');if($d['IsTeacher']??false)DB::table('Teachers')->insert(['TenantId'=>$t->id(),'EmployeeId'=>$id]);return $this->ok(DB::table('Employees')->where('EmployeeId',$id)->first(),'Employee created.',201);}return $this->ok(DB::table('Employees')->where('TenantId',$t->id())->orderBy('FullName')->get(),'Employees retrieved.');}
 public function attendance(Request $r,TenantContext $t){if($r->isMethod('post')){$d=$r->validate(['BranchId'=>['required','integer'],'AttendanceDate'=>['required','date'],'Records'=>['required','array'],'Records.*.EmployeeId'=>['required','integer'],'Records.*.Status'=>['required',Rule::in(['Present','Absent','Late','Leave','Sick','Holiday'])]]);foreach($d['Records'] as $x)DB::table('EmployeeAttendances')->updateOrInsert(['TenantId'=>$t->id(),'EmployeeId'=>$x['EmployeeId'],'AttendanceDate'=>$d['AttendanceDate']],['BranchId'=>$d['BranchId'],'Status'=>$x['Status'],'CreatedAt'=>now()]);return $this->ok((object)[],'Employee attendance saved.');}return $this->ok(DB::table('EmployeeAttendances')->join('Employees','EmployeeAttendances.EmployeeId','=','Employees.EmployeeId')->where('EmployeeAttendances.TenantId',$t->id())->select('EmployeeAttendances.*','Employees.FullName','Employees.EmployeeNo')->orderByDesc('AttendanceDate')->get(),'Employee attendance retrieved.');}
 public function payroll(Request $r,TenantContext $t){if($r->isMethod('post')){$d=$r->validate(['BranchId'=>['required','integer'],'EmployeeId'=>['required','integer'],'PayPeriodMonth'=>['required','integer','between:1,12'],'PayPeriodYear'=>['required','integer'],'Allowances'=>['nullable','numeric'],'Deductions'=>['nullable','numeric']]);$e=DB::table('Employees')->where('TenantId',$t->id())->where('EmployeeId',$d['EmployeeId'])->first();abort_unless($e,404);$net=$e->BasicSalary+($d['Allowances']??0)-($d['Deductions']??0);$id=DB::table('Payrolls')->insertGetId(['TenantId'=>$t->id(),'BasicSalary'=>$e->BasicSalary,'NetSalary'=>$net,'Status'=>'Pending','CreatedAt'=>now(),...$d],'PayrollId');return $this->ok(DB::table('Payrolls')->where('PayrollId',$id)->first(),'Payroll prepared.',201);}return $this->ok(DB::table('Payrolls')->join('Employees','Payrolls.EmployeeId','=','Employees.EmployeeId')->where('Payrolls.TenantId',$t->id())->select('Payrolls.*','Employees.FullName','Employees.EmployeeNo')->orderByDesc('PayrollId')->get(),'Payroll retrieved.');}
 private function ok(mixed $data,string $message,int $status=200){return response()->json(['success'=>true,'message'=>$message,'data'=>$data,'meta'=>(object)[]],$status);}
}
