<?php
namespace App\Http\Controllers\Api;
use App\Jobs\SendQueuedSms;
use App\Http\Controllers\Controller;use App\Models\User;use App\Tenancy\TenantContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;use Illuminate\Validation\Rule;
class SystemController extends Controller
{
 public function settings(Request $r,TenantContext $t){if($r->isMethod('put')){$d=$r->validate(['SchoolName'=>['required','string'],'Phone'=>['nullable','string'],'Email'=>['nullable','email'],'Address'=>['nullable','string'],'Currency'=>['required','string','size:3'],'Timezone'=>['required','string'],'DefaultLanguage'=>['required',Rule::in(['so','en','ar'])],'ReceiptNumberFormat'=>['required','string'],'InvoiceNumberFormat'=>['required','string'],'AdmissionNumberFormat'=>['required','string'],'CertificateNumberFormat'=>['required','string'],'AttendanceLockHours'=>['required','integer','min:0']]);DB::table('TenantSettings')->updateOrInsert(['TenantId'=>$t->id()],['CreatedAt'=>now(),'UpdatedAt'=>now(),...$d]);DB::table('Tenants')->where('TenantId',$t->id())->update(['Name'=>$d['SchoolName'],'Timezone'=>$d['Timezone'],'Currency'=>$d['Currency'],'UpdatedAt'=>now()]);return $this->ok(DB::table('TenantSettings')->where('TenantId',$t->id())->first(),'Settings updated.');}$row=DB::table('TenantSettings')->where('TenantId',$t->id())->first()??DB::table('Tenants')->where('TenantId',$t->id())->select('Name as SchoolName','Timezone','Currency')->first();return $this->ok($row,'Settings retrieved.');}
 public function feedback(Request $r,TenantContext $t){if($r->isMethod('post')){$d=$r->validate(['Category'=>['required',Rule::in(['Suggestion','Complaint','Question','Other'])],'Priority'=>['required',Rule::in(['Low','Normal','High','Urgent'])],'Subject'=>['required','string'],'Description'=>['required','string'],'IsAnonymous'=>['boolean']]);$id=DB::table('Suggestions')->insertGetId(['TenantId'=>$t->id(),'SubmittedByUserId'=>$d['IsAnonymous']?null:$t->user()->UserId,'Status'=>'Open','CreatedAt'=>now(),...$d],'SuggestionId');return $this->ok(DB::table('Suggestions')->where('SuggestionId',$id)->first(),'Feedback submitted.',201);}return $this->ok(DB::table('Suggestions')->where('TenantId',$t->id())->orderByDesc('SuggestionId')->get(),'Feedback retrieved.');}
 public function respond(Request $r,int $feedback,TenantContext $t){$d=$r->validate(['Response'=>['required','string'],'Status'=>['required',Rule::in(['Assigned','In progress','Resolved','Closed'])]]);DB::table('Suggestions')->where('TenantId',$t->id())->where('SuggestionId',$feedback)->update([...$d,'AssignedUserId'=>$t->user()->UserId,'ResolvedAt'=>in_array($d['Status'],['Resolved','Closed'])?now():null]);return $this->ok((object)[],'Feedback updated.');}
 public function smsTemplates(Request $r,TenantContext $t){if($r->isMethod('post')){$d=$r->validate(['TemplateName'=>['required','string'],'TemplateBody'=>['required','string','max:500']]);$id=DB::table('SmsTemplates')->insertGetId(['TenantId'=>$t->id(),...$d],'SmsTemplateId');return $this->ok(DB::table('SmsTemplates')->where('SmsTemplateId',$id)->first(),'SMS template created.',201);}return $this->ok(DB::table('SmsTemplates')->where('TenantId',$t->id())->get(),'SMS templates retrieved.');}
 public function smsSettings(Request $r,TenantContext $t){if($r->isMethod('put')){$d=$r->validate(['ProviderName'=>['required','string'],'ApiKey'=>['required','string'],'SenderId'=>['required','string'],'IsActive'=>['boolean']]);DB::table('SmsSettings')->updateOrInsert(['TenantId'=>$t->id()],['ProviderName'=>$d['ProviderName'],'EncryptedCredentials'=>Crypt::encryptString($d['ApiKey']),'SenderId'=>$d['SenderId'],'IsActive'=>$d['IsActive']??true]);return $this->ok((object)[],'SMS provider saved securely.');}$row=DB::table('SmsSettings')->where('TenantId',$t->id())->first();if($row)$row->EncryptedCredentials=$row->EncryptedCredentials?'Configured':null;return $this->ok($row,'SMS settings retrieved.');}
 public function sendSms(Request $r,TenantContext $t){$d=$r->validate(['RecipientPhone'=>['required','string'],'MessageBody'=>['required','string','max:500'],'SmsTemplateId'=>['nullable','integer'],'ScheduledAt'=>['nullable','date']]);$id=DB::table('SmsLogs')->insertGetId(['TenantId'=>$t->id(),'Status'=>'Queued','Attempts'=>0,'CreatedByUserId'=>$t->user()->UserId,'CreatedAt'=>now(),...$d],'SmsLogId');$pending=SendQueuedSms::dispatch($id);if(!empty($d['ScheduledAt']))$pending->delay($d['ScheduledAt']);return $this->ok(DB::table('SmsLogs')->where('SmsLogId',$id)->first(),'SMS queued.',201);}
 public function smsLogs(TenantContext $t){return $this->ok(DB::table('SmsLogs')->where('TenantId',$t->id())->orderByDesc('SmsLogId')->get(),'SMS delivery records retrieved.');}
 public function users(Request $r,TenantContext $t){if($r->isMethod('post')){$d=$r->validate(['Name'=>['required','string'],'Email'=>['required','email'],'Password'=>['required','string','min:10'],'BranchIds'=>['required','array','min:1'],'RoleIds'=>['nullable','array']]);$id=DB::transaction(function()use($d,$t){$id=DB::table('Users')->insertGetId(['TenantId'=>$t->id(),'Name'=>$d['Name'],'Email'=>$d['Email'],'Password'=>Hash::make($d['Password']),'Status'=>'Active','CreatedAt'=>now(),'UpdatedAt'=>now()],'UserId');foreach($d['BranchIds'] as $b){abort_unless(DB::table('Branches')->where('TenantId',$t->id())->where('BranchId',$b)->exists(),422);DB::table('UserBranches')->insert(['TenantId'=>$t->id(),'UserId'=>$id,'BranchId'=>$b]);}foreach($d['RoleIds']??[] as $role)DB::table('UserRoles')->insert(['UserId'=>$id,'RoleId'=>$role,'TenantId'=>$t->id()]);return $id;});return $this->ok(User::find($id),'User created.',201);}return $this->ok(DB::table('Users')->where('TenantId',$t->id())->select('UserId','Name','Email','Status','CreatedAt')->get(),'Users retrieved.');}
 public function roles(Request $r,TenantContext $t){if($r->isMethod('post')){$d=$r->validate(['RoleName'=>['required','string'],'PermissionIds'=>['required','array']]);$id=DB::transaction(function()use($d,$t){$id=DB::table('Roles')->insertGetId(['TenantId'=>$t->id(),'RoleName'=>$d['RoleName'],'IsSystemRole'=>false,'CreatedAt'=>now()],'RoleId');foreach($d['PermissionIds'] as $p)DB::table('RolePermissions')->insert(['RoleId'=>$id,'PermissionId'=>$p]);return $id;});return $this->ok(DB::table('Roles')->where('RoleId',$id)->first(),'Role created.',201);}return $this->ok(['roles'=>DB::table('Roles')->where(fn($q)=>$q->where('TenantId',$t->id())->orWhereNull('TenantId'))->get(),'permissions'=>DB::table('Permissions')->orderBy('ModuleName')->get()],'Roles and permissions retrieved.');}
 public function audits(TenantContext $t){return $this->ok(DB::table('AuditLogs')->leftJoin('Users','AuditLogs.UserId','=','Users.UserId')->where('AuditLogs.TenantId',$t->id())->select('AuditLogs.*','Users.Name as UserName')->orderByDesc('AuditLogId')->limit(500)->get(),'Audit logs retrieved.');}
 public function reports(TenantContext $t){$tid=$t->id();$tables=['Students','Attendance','QuranAssignments','QuranAssessments','Invoices','Payments','Expenses','Employees','Exams','SmsLogs','Users','AuditLogs'];$data=[];foreach($tables as $x)$data[$x]=DB::table($x)->where('TenantId',$tid)->count();return $this->ok($data,'Report catalogue metrics retrieved.');}
 private function ok(mixed $data,string $message,int $status=200){return response()->json(['success'=>true,'message'=>$message,'data'=>$data,'meta'=>(object)[]],$status);}
}
